window.JOURNALS_DATA = [
    { icon: 'ph-chart-bar', title: 'IUEA Journal of Business & Management', desc: 'An open access, peer-reviewed journal publishing contemporary research in business, management, and entrepreneurship.', fullDesc: 'The IUEA Journal of Business & Management is a double-blind peer-reviewed, open access journal dedicated to publishing high-quality original research. We welcome submissions covering all areas of business administration, management theory, corporate governance, organizational behavior, marketing, finance, and entrepreneurship. Our goal is to bridge the gap between academic research and business practice, particularly within the dynamic economic landscape of East Africa and emerging markets globally.', freq: 'Biannual', accent: '#8B1A1A', vol: 'Vol. 8', issn: '2663-3818', acronym: 'IUEA-B&M', featured: true },
    { icon: 'ph-flask', title: 'International Journal of Science & Technology', desc: 'Publishing contemporary and novel research in applied sciences, engineering, and emerging technologies.', fullDesc: 'The International Journal of Science & Technology publishes cutting-edge research across all fields of applied science, engineering, computing, and technology. We focus on innovative methodologies, experimental studies, and technological advancements that address real-world problems. The journal provides a platform for scientists, engineers, and researchers to share their discoveries and contribute to the technological advancement of society.', freq: 'Biannual', accent: '#1f5f8b', vol: 'Vol. 7', issn: '2707-0868', acronym: 'IUEA-S&T' },
    { icon: 'ph-scales', title: 'IUEA Law Journal', desc: 'The official journal of the Faculty of Law, covering legal theory, practice, and policy in East Africa and beyond.', fullDesc: 'The IUEA Law Journal is the flagship publication of the Faculty of Law at the International University of East Africa. It serves as a forum for rigorous legal scholarship, critical analysis, and debate on a wide range of legal topics. We publish articles, case notes, and book reviews that explore legal theory, jurisprudence, domestic and international law, human rights, and legal policy, with a special emphasis on legal developments affecting the African continent.', freq: 'Annual', accent: '#7a6200', vol: 'Vol. 5', issn: '2519-5138', acronym: 'IUEA-LAW' },
    { icon: 'ph-heartbeat', title: 'IUEA Journal of Health & Environmental Studies', desc: 'Public health, environmental sustainability, and community wellbeing research.', fullDesc: 'This journal focuses on the critical intersection of human health and the environment. We publish peer-reviewed research on public health initiatives, epidemiology, environmental science, sustainable development, and community wellbeing. Our mission is to promote research that leads to actionable solutions for environmental challenges and improves health outcomes in diverse populations.', freq: 'Annual', accent: '#2e7d32', vol: 'Vol. 4', issn: '2814-1353', acronym: 'IUEA-HES' },
    { icon: 'ph-users-three', title: 'IUEA Journal of Social Sciences & Humanities', desc: 'Studies on governance, culture, education, and society shaping Africa’s future.', fullDesc: 'The IUEA Journal of Social Sciences & Humanities provides an interdisciplinary platform for research that explores the complexities of human society, culture, and governance. We invite contributions from sociology, political science, history, linguistics, education, and the arts. The journal aims to foster a deeper understanding of societal transformations, cultural heritage, and the educational paradigms that are shaping the future of Africa and the world.', freq: 'Biannual', accent: '#6a3d9a', vol: 'Vol. 6', issn: '2707-085X', acronym: 'IUEA-SSH' },
    { icon: 'ph-graduation-cap', title: 'IUEA Student Research Digest', desc: 'A platform for outstanding undergraduate and postgraduate research from IUEA students.', fullDesc: 'The IUEA Student Research Digest is dedicated to showcasing the exceptional scholarly work of undergraduate and postgraduate students at the International University of East Africa. This publication provides students with a valuable opportunity to experience the peer-review process, disseminate their research findings, and contribute to academic discourse across various disciplines.', freq: 'Annual', accent: '#b45f17', vol: 'Vol. 3', issn: '2916-0623', acronym: 'IUEA-SRD' }
];

window.ISSUE_SAMPLES_DATA = [
    { title: 'Determinants of SME growth in Kampala', year: 2024 },
    { title: 'Solar microgrid adoption in rural East Africa', year: 2024 },
    { title: 'Mobile banking and financial inclusion', year: 2023 }
];
